<?php
session_start();
require_once __DIR__ . '/admin/inc/db.php';
require_once __DIR__ . '/inc/language.php';
if (empty($_SESSION['user_id']) || empty($_SESSION['user_email']) && empty($_SESSION['email'])) { header('Location: login.php'); exit; }
$farmerEmail = mysqli_real_escape_string($db, $_SESSION['user_email'] ?? $_SESSION['email']);
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['update_inquiry'])) {
    $inquiryId = (int) $_POST['inquiry_id']; $status = max(0, min(2, (int) $_POST['status'])); $response = mysqli_real_escape_string($db, trim($_POST['response'] ?? ''));
    mysqli_query($db, "UPDATE product_inquiries i INNER JOIN products p ON p.product_id=i.product_id SET i.status='$status', i.response='$response', i.updated_at=NOW() WHERE i.inquiry_id='$inquiryId' AND p.seller_email='$farmerEmail'");
}
$inquiries = mysqli_query($db, "SELECT i.*, p.product_name, u.user_name, u.user_email FROM product_inquiries i INNER JOIN products p ON p.product_id=i.product_id LEFT JOIN users u ON u.user_id=i.buyer_id WHERE p.seller_email='$farmerEmail' ORDER BY i.created_at DESC");
$labels = ['Pending', 'Responded', 'Resolved']; $classes = ['warning', 'info', 'success'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Farmer Inquiries</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><div class="container py-5"><div class="card shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h3>Buyer Inquiries</h3><a href="farmerDashboard.php?do=Home" class="btn btn-outline-secondary">Back</a></div><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Product</th><th>Buyer</th><th>Subject</th><th>Message</th><th>Status</th><th>Respond</th></tr></thead><tbody><?php if ($inquiries && mysqli_num_rows($inquiries)) { while ($inquiry = mysqli_fetch_assoc($inquiries)) { $status = (int) $inquiry['status']; ?><tr><td><?php echo htmlspecialchars($inquiry['product_name']); ?></td><td><?php echo htmlspecialchars($inquiry['user_name'] ?: $inquiry['buyer_email']); ?></td><td><?php echo htmlspecialchars($inquiry['subject']); ?></td><td><?php echo nl2br(htmlspecialchars($inquiry['message'])); ?></td><td><span class="badge text-bg-<?php echo $classes[$status] ?? 'secondary'; ?>"><?php echo $labels[$status] ?? 'Pending'; ?></span></td><td><form method="post"><input type="hidden" name="inquiry_id" value="<?php echo (int) $inquiry['inquiry_id']; ?>"><select name="status" class="form-select form-select-sm mb-2"><option value="0" <?php echo $status === 0 ? 'selected' : ''; ?>>Pending</option><option value="1" <?php echo $status === 1 ? 'selected' : ''; ?>>Responded</option><option value="2" <?php echo $status === 2 ? 'selected' : ''; ?>>Resolved</option></select><textarea name="response" class="form-control form-control-sm mb-2" rows="2"><?php echo htmlspecialchars($inquiry['response'] ?? ''); ?></textarea><button name="update_inquiry" class="btn btn-sm btn-success">Send Response</button></form></td></tr><?php } } else { ?><tr><td colspan="6" class="text-center text-muted">No buyer inquiries yet.</td></tr><?php } ?></tbody></table></div></div></div></div></body></html>
