<?php
session_start();
require_once __DIR__ . '/admin/inc/db.php';
require_once __DIR__ . '/inc/language.php';
if (empty($_SESSION['user_id'])) { header('Location: login.php'); exit; }
$buyerId = (int) $_SESSION['user_id'];
$inquiries = mysqli_query($db, "SELECT i.*, p.product_name FROM product_inquiries i LEFT JOIN products p ON p.product_id=i.product_id WHERE i.buyer_id='$buyerId' ORDER BY i.created_at DESC");
$labels = ['Pending', 'Responded', 'Resolved']; $classes = ['warning', 'info', 'success'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Inquiry History</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><div class="container py-5"><div class="card shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h3>Inquiry History</h3><a href="customerDashboard.php" class="btn btn-outline-secondary">Back</a></div><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Product</th><th>Subject</th><th>Message</th><th>Status</th><th>Response</th><th>Date</th></tr></thead><tbody><?php if ($inquiries && mysqli_num_rows($inquiries)) { while ($inquiry = mysqli_fetch_assoc($inquiries)) { $status = (int) $inquiry['status']; ?><tr><td><?php echo htmlspecialchars($inquiry['product_name'] ?: 'Unavailable'); ?></td><td><?php echo htmlspecialchars($inquiry['subject']); ?></td><td><?php echo nl2br(htmlspecialchars($inquiry['message'])); ?></td><td><span class="badge text-bg-<?php echo $classes[$status] ?? 'secondary'; ?>"><?php echo $labels[$status] ?? 'Pending'; ?></span></td><td><?php echo nl2br(htmlspecialchars($inquiry['response'] ?? 'Awaiting response')); ?></td><td><?php echo htmlspecialchars($inquiry['created_at']); ?></td></tr><?php } } else { ?><tr><td colspan="6" class="text-center text-muted">No inquiries yet.</td></tr><?php } ?></tbody></table></div></div></div></div></body></html>
